package org.cyk.ui.api.command;

//TODO use interface for easy substitution
@Deprecated
public enum IconType{
	ACTION_GO_BACK,ACTION_OK,ACTION_APPLY,ACTION_SAVE,ACTION_ADD,ACTION_UPDATE,ACTION_DELETE,ACTION_CLEAR,ACTION_EDIT,ACTION_CANCEL,ACTION_REMOVE,ACTION_OPEN
	,ACTION_ADMINISTRATE,ACTION_HELP,ACTION_PREVIEW,ACTION_SEARCH,ACTION_EXPORT,ACTION_EXPORT_PDF,ACTION_EXPORT_EXCEL,ACTION_LOGOUT,ACTION_PRINT,ACTION_DOWNLOAD
	
	,THING_APPLICATION,THING_LICENCE,THING_TOOLS,THING_CALENDAR,THING_AGENDA,THING_USERACCOUNT,THING_CONTROLPANEL,THING_LIST,THING_FOLDER_COLLAPSED,THING_FOLDER_EXPANDED
	,THING_TABLE
	
	,PERSON, ACTION_SET, THING_SECURITY, THING_NOTIFICATIONS, THING_HELP, THING_REPORT, THING_HOME, THING_CONNECTED,THING_URL,THING_ROLE,THING_MONEY
	
	;
}